INSERT INTO Alalumilaadut (Alatyypin_nimi, Lumilaatu_ID, Hiihdettavyys) 
VALUES ('Vitilumi',6,5),
('Puuteri',6,5),
('Kostea uusilumi',6,4),
('Sastrugi',7,2),
('Aaltoileva lumi',7,3),
('Tuiskulumi',7,4),
('Ohut korppu',3,3),
('Rikkoutuva korppu',3,2),
('Kantava korppu',3,4),
('Jää',5,3),
('Haurastuva jää',5,4),
('Kastuva',4,5),
('Saturoitunut',4,2),
('Kiviä',10,NULL),
('Oksia',10,NULL),
('Kantoja',10,NULL);
