INSERT INTO Lumilaadut(ID, Nimi, Vari, Hiihdettavyys, Kategoria_ID, Lumityyppi_selite)
VALUES  (1,'Korppu','#3838a0',3,NULL,'Kova hangen pinnalla oleva kansi. Korppu voi olla luonteeltaan tasaista tai rosoista.'),
        (2,'Sohjo','#919394',2,NULL,'Vesipitoinen ja osittain sulanut lumi suojasäällä.'),
        (3,'Jää','#34929A',2,NULL,'Hangen pinnalla oleva kova ja rikkoutumaton jäinen kerros. Jää on syntynyt sulamis-jäätymisreaktion tuloksena.'),
        (4,'Uusi lumi','#5AABED',4,NULL,'Vastasatanut pehmeä lumi.'),
        (5,'Tuulen pieksemä lumi','#7C759F',3,NULL,'Tuulen kovettama ja moninpaikoin epätasaiseksi muotoilema lumi.'),
        (6,'Vähäinen lumi','#6D4F32',NULL,NULL,''),
        (7,'Lumeton maa',"#000000",NULL,NULL,''),
        (8,'Vitilumi','#5AABED',5,4,'Vastasatanutta, kevyttä, pehmeää ja hieman tiivistyvää pakkaslunta.'),
        (9,'Puuterilumi','#5AABED',5,4,'Vastasatanutta irtonaista, höyhenenkevyttä ja tiivistymätöntä lunta. Puuterilunta muodostuu yleensä tyynellä ilmalla ja kovalla pakkasella.'),
        (10,'Märkä uusi lumi','#5AABED',4,4,'Lunta, josta voit helposti tehdä lumipallon. Märkää lunta muodostuu sateen tapahtuessa lähellä nollaa tai reilusti suojan puolella.'),
        (11,'Sastrugi','#7C759F',1,5,'Tuulen aiheuttamaa lumiaallokkoa, joka on kovaa, jäistä ja terväharjanteista.'),
        (12,'Aaltoileva lumi','#7C759F',4,5,'Tuulen muotoilema uuden lumen alue. Aallot ovat pehmeitä ja hyvin rikottavissa.'),
        (13,'Tuiskulumi','#7C759F',4,5,'Tasainen, tuulen kerrostama ja pakkaama laatta tai linssi. Tuiskulunta voi kertyä myös ilman lumisadetta, jos tuuli siirtää lunta paikasta toiseen. Tuiskulunta syntyy yleensä suojapuolelle.'),
        (14,'Ohut korppu','#3838a0',3,1,'Hiihtäjän painosta rikkoutuva lumikansi. Korpun alla lumi voi olla paikoitellen upottavaa.'),
        (15,'Rikkoutuva korppu','#3838a0',2,1,'Satunnaisesti kantava, yllättäen rikkoutuva lumen pinta. Kansi voi olla hyvinkin paksu, jos sen alla on huokoista lunta.'),
        (16,'Kantava korppu','#3838a0',3,1,'Tukeva ja kantava lumikansi, jonka pinta on usein hyvin kovaa ja tiivistä.'),
        (17,'Rikkoutuva jää','#34929A',1,3,'Hangen pinnalla oleva kova ja rikkoutuva jäinen kerros.'),
        (18,'Kastuva lumi','#919394',3,2,'Lämpenemisen tai vesisateen myötä pinnalta alkaen märkä tai kostea lumi.'),
        (19,'Saturoitunut lumi','#919394',2,2,'Märkä, läpi koko kerroksen sohjoutuva ja kermavaahtomainen lumi'),
        (20,'Kiviä','#4B4B4B',NULL,7,''),
        (21,'Oksia','#6D4F32',NULL,7,'');
